export interface Spell {
    "name": string,
    "id": number,
    "level": number,
    "school": string,
    "castingTime"?: string,
    "range"?: string,
    "areaOrTargets"?: string,
    "effect": string,
    "saveOrAttack"?: string,
    "duration"?: string,
    "mats"?: string,
    "conc"?: string,
    "source"?: string,
    "page"?: number,
    "ritual"?:string,
    "arcaneTrickster": boolean,
    "bard": boolean,
    "cleric": boolean,
    "druid": boolean,
    "eldritchKnight": boolean,
    "paladin": boolean,
    "ranger": boolean,
    "sorcerer": boolean,
    "warlock": boolean,
    "wizard": boolean,
    "cost"?:any,
}
